server:
  port: "8080"
  enable_ui: true

database:
  host: "localhost"
  port: "5432"
  user: "user"
  password: "password"
  name: "delayed_notifier"

rabbitmq:
  url: "amqp://guest:guest@localhost:5672/"
